version: "3"
volumes:
  db-volume: { }
services:
  web:
    depends_on:
      - db
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: ./Dockerfile-web
#    volumes:
#      - ./:/sap
    ports:
      - "3001:3001"

  db:
    build:
      context: .
      dockerfile: ./Dockerfile-db
    environment:
      - POSTGRES_PASSWORD=trust
    ports:
      - "5432:5432"
    volumes:
      - db-volume:/var/lib/postgresql/data
